apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }} # Everytime a pod is created, it will pull the image from the registry. In production, you may want to pin a specific version to avoid unexpected upgrades.

        ports:
        - containerPort: {{ .Values.containerPort }}

        env:
        {{- range .Values.containerEnvVars }}
        - name: {{ .name }}
          valueFrom:
        {{- if .configMapKeyRef }}
            configMapKeyRef:
              name: {{ .configMapKeyRef.name }}
              key: {{ .configMapKeyRef.key }}
        {{- end }}
        {{- if .secretKeyRef }}
            secretKeyRef:
              name: {{ .secretKeyRef.name }}
              key: {{ .secretKeyRef.key }}
        {{- end }}
        {{- end }}